Major update Oct 1-11, 2014 (RZ). Modifications summarized in "CHANGES" file.

diff --git a/bin/evaluate b/bin/evaluate
--- a/bin/evaluate
+++ b/bin/evaluate
@@ -10,103 +10,189 @@
 # in your .bashrc file (the initialization file for bash shell). The PATH
 # alteration will add the tools to your search path. 
 
-if [ $# -lt 2 ]
+if [ $# -lt 1 ]
 then
-	echo "LgEval Label graph evaluation tool"
-	echo "Copyright (c) R. Zanibbi, H. Mouchere, 2012-2013"
+	echo "LgEval evaluate: Label graph evaluation tool"
+	echo "Copyright (c) R. Zanibbi, H. Mouchere, 2012-2014"
 	echo ""
-	echo "Usage: evaluate outputDir groundTruthDir [t/d/s/b]"
+	echo "Usage: evaluate outputDir groundTruthDir [p/t/d/s/b] OR"
+	echo "       evaluate fileList [p/t/d/s/b]"
 	echo ""
 	echo "Evaluates all label graph (.lg) files in outputDir against"
 	echo "corresponding files in groundTruthDir. groundTruthDir is used"
 	echo "to generate the list of files to be compared (i.e. if a file is"
 	echo "not in the ground truth directory, it will not be considered)."
 	echo ""
+	echo "If a list of files is provided instead ('output target' on each line)"
+	echo "then these file pairs are used for evaluation."
+	echo ""
 	echo "Outputs"
 	echo "-----------------------------"
-	echo " Results<outputDir>/"
-	echo "    Summary : summary of performance metrics"
-	echo "    Correct : list outputDir files matching ground truth"
-	echo "    Metrics.m : metrics for all .lg files compared"
-	echo "    Diffs.diff : all differences between files"
-	echo "    ConfusionMatrix.html : node and edge label confusion matrix"
-	echo "        (errors only)"
+	echo " Results<outputDir/fileListName>/"
+	echo "    00_RawResults.csv:      raw metrics spreadsheet"
+	echo "    00_Summary.txt:         summary of performance metrics"
+	echo "    ConfusionMatrices.csv/.html:  confusion matrix spreadsheet (errors)"
+	echo "    FileResults.csv: all evaluated files, with correct/incorrect indication"
 	echo "" 
-	echo "    Metrics/ : directory with .m (metric) and .diff (difference) file for"
-	echo "      each comparison. .dot (GraphViz) and .pdf files are generated for"
-	echo "      viewing differences between files if a third argument is provided."
+	echo "    Metrics/: directory with .csv (metric) and .diff (difference) files"
+	echo "    graphErrors/: if dot output requested, visualizations for files with"
+	echo "      errors are stored here (.dot and .pdf format)."
 	echo ""
 	echo "NOTE: the different visualizations of structural differences are described"
 	echo "      if you run lg2dot without arguments (object (t)ree; (d)irected graph"
 	echo "      over objects; primitive (s)egmentation graph; (b)ipartite graph over"
-	echo "      primitives."
+	echo "      primitives; (p): default directed graph over primitives."
 	exit 0
 fi
 
-dir=$1
+DOTARG=""
 BNAME=`basename $1`
-truthDir=$2
-ResultsDir=Results_$BNAME
+MODE="Dir"
 
+TARGETS=""
+OUTPUTS=""
+if ! [ -d $1 ]
+then
+	echo "File List: $1"
+	MODE="List"
+	# Get the targets
+	OUTPUTS=`awk '{ print $1; }' $1`
+	OUTARR=($OUTPUTS)
+	TARGETS=`awk '{ print $2; }' $1`
+
+	if [ $# -gt 1 ]
+	then
+		DOTARG=$2
+	fi
+else
+	echo "Output File Directory:  $1"
+	echo "Ground Truth Directory: $2"
+
+	TARGETS=`ls $2/*.lg`
+
+	if [ $# -gt 2 ]
+	then
+		DOTARG=$3
+	fi
+fi
+echo ""
+
+ResultsDir=Results_$BNAME
 if ! [ -d $ResultsDir ]
 then
 	mkdir $ResultsDir
 	mkdir $ResultsDir/Metrics
+
+	if [ "$DOTARG" != "" ]
+	then
+		mkdir $ResultsDir/errorGraphs
+		mkdir $ResultsDir/errorGraphs/dot
+		mkdir $ResultsDir/errorGraphs/pdf
+	fi
 fi
 
-echo "Output File Directory:  $1"
-echo "Ground Truth Directory: $2"
-echo ""
 
-# Compute all .m metrics outputs (per-file), and .diff results (per-file).
+# Compute all .csv metrics outputs (per-file), and .diff results (per-file).
 echo "Evaluating files..."
-PREFIX=res_
-for file in `ls $truthDir/*.lg`
+
+INDEX=0
+for file in $TARGETS
 do
 	FNAME=`basename $file .lg`
-	nextFile=$dir/$FNAME.lg
-	if  [[ ! -e $ResultsDir/Metrics/$FNAME.m ]]
+	nextFile="_ERROR_"
+	if [ $MODE == "Dir" ]
+	then
+		nextFile=`echo "$1/$FNAME.lg" | perl -p -i -e "s/\/\//\//g"`
+	else
+		# Index to the next input file.
+		nextFile=${OUTARR[INDEX]}
+	fi
+
+	if  [[ ! -e $ResultsDir/Metrics/$FNAME.csv ]]
 	then
 		# NOTE: the script convertCrohmeLg can be used to convert
 		#       crohme .inkml files to .lg files.
 		echo "  >> Comparing $FNAME.lg"
 
-		python $LgEvalDir/src/evallg.py $nextFile $file m > $ResultsDir/Metrics/$FNAME.m
-		DIFF=`python $LgEvalDir/src/evallg.py $nextFile $file diff`
+		python $LgEvalDir/src/evallg.py $nextFile $file m INTER > $ResultsDir/Metrics/$FNAME.csv
+		DIFF=`python $LgEvalDir/src/evallg.py $nextFile $file diff INTER`
+		CORRECT="Correct"
 		if [ -n "$DIFF" ]
 		then
 			echo "$DIFF" > $ResultsDir/Metrics/$FNAME.diff 
+			# Record files with errors in the "Errors" file.
+			#echo "$nextFile" >> $ResultsDir/FilesIncorrect.txt
 
 			# If a third argument is provided, generate a .pdf file to visualize
 			# differences between graphs.
-			if [ $# -gt 2 ]
+			if [ "$DOTARG" != "" ]
 			then
-				lg2dot $nextFile $file $3 
-				mv $FNAME.dot $FNAME.pdf $ResultsDir/Metrics/
+				if [ "$DOTARG" == "p" ]
+				then
+					lg2dot $nextFile $file
+				else
+					lg2dot $nextFile $file "$DOTARG"
+				fi
+				mv $FNAME.dot $ResultsDir/errorGraphs/dot
+				mv $FNAME.pdf $ResultsDir/errorGraphs/pdf
 			fi
+			
+			CORRECT="Incorrect"
 		else
 			rm -f $ResultsDir/Metrics/$FNAME.diff
-			echo "$nextFile" >> $ResultsDir/Correct
+			# Record correct files in the "Correct" file.
+			#echo "$nextFile" >> $ResultsDir/FilesCorrect.txt
 		fi
+
+		# Add record of evaluating the file.
+		echo "$nextFile, $CORRECT" >> $ResultsDir/FileResults.csv
 	else
 		echo "    Already processed: $file"
 	fi
+
+	INDEX=$((INDEX+1))
 done
 
 # Compile all metrics/diffs,
 # and then compute metric summaries and confusion matrices.
-cat $ResultsDir/Metrics/*.m > $ResultsDir/Metrics.m
+cat $ResultsDir/Metrics/*.csv > $ResultsDir/$BNAME.csv
 ALLDIFFS=`ls $ResultsDir/Metrics | grep .diff`
 if [ -n "$ALLDIFFS" ]
 then
-	cat $ResultsDir/Metrics/*.diff > $ResultsDir/Diffs.diff
+	cat $ResultsDir/Metrics/*.diff > $ResultsDir/$BNAME.diff
 else
-	touch $ResultsDir/__NoErrors
-	touch $ResultsDir/Diffs.diff  # empty - no errors.
+	touch $ResultsDir/00_NoErrors
+	touch $ResultsDir/$BNAME.diff  # empty - no errors.
 fi
 
-python $LgEvalDir/src/sumMetric.py $ResultsDir/Metrics.m > $ResultsDir/__Summary
-python $LgEvalDir/src/sumDiff.py $ResultsDir/Diffs.diff html > $ResultsDir/ConfusionMatrix.html
+python $LgEvalDir/src/sumMetric.py $ResultsDir/$BNAME.csv > $ResultsDir/00_Summary.txt
+python $LgEvalDir/src/sumDiff.py $ResultsDir/$BNAME.diff html > $ResultsDir/ConfusionMatrices.html
+python $LgEvalDir/src/sumDiff.py $ResultsDir/$BNAME.diff > $ResultsDir/ConfusionMatrices.csv
+
+# RZ Oct. 2014: Create spreadsheet pairing file names with metrics.
+# Clean up raw metric data to make the file smaller and simpler.
+# Use awk and head to select every odd (headers) and even (data) columns,
+# Concatenate one header row with data contents.
+awk -F',' '{ for (i=1;i<=NF;i+=2) printf ("%s%c", $i, i + 2 <= NF ? "," : "\n")}' $ResultsDir/$BNAME.csv > $ResultsDir/Headers.csv
+
+# Obtain first row for data labels; insert a "File" label in the first column.
+head -n 1 $ResultsDir/Headers.csv > $ResultsDir/HeaderRow.csv
+HEAD=`cat $ResultsDir/HeaderRow.csv`
+echo "File,Result,$HEAD" > $ResultsDir/HeaderRow.csv
+
+awk -F',' '{ for (i=2;i<=NF;i+=2) printf ("%s%c", $i, i + 2 <= NF ? "," : "\n")}' $ResultsDir/$BNAME.csv > $ResultsDir/Data.csv
+
+# Combine file names with raw data metrics, then add header labels.
+paste -d , $ResultsDir/FileResults.csv $ResultsDir/Data.csv > $ResultsDir/DataNew.csv
+cat $ResultsDir/HeaderRow.csv $ResultsDir/DataNew.csv > $ResultsDir/00_RawResults.csv
+
+# Clean up.
+rm -f $ResultsDir/Headers.csv $ResultsDir/HeaderRow.csv $ResultsDir/Data.csv
+rm -f $ResultsDir/DataNew.csv
+
+# Remove the compiled metrics and differences, but leave the individual metric/diff
+# files in Metrics to support debugging for malformed or missing files, etc.
+rm -f $ResultsDir/$BNAME.csv $ResultsDir/$BNAME.diff
 
 echo "done."
 
